name: Publish

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/cross-test/workerd-manager
          key: ${{ runner.os }}-cross-test-workerd-manager
      - name: Build
        run: |
          deno task build
      - name: Lint
        run: |
          deno lint
          deno fmt --check
      - name: Run test
        run: |
          deno task test
      - name: Publish
        run: |
          deno publish
